### PR TITLE
Add all test cases in a package with a single line

### PR DESCRIPTION
**Pull request by RealyUniqueName**
```haxe
var runner = new Runner();
runner.addCases('mypack.tests');
```
See https://github.com/RealyUniqueName/utest/blob/add-multiple-cases/test/utest/TestRunner.hx for an example

### CODE REVIEW

**Comment by fponticelli** [comment]
I like it! Does the package need to be a string? Couldn't it be an identifier? It might make for a cleaner syntax, maybe?

**Comment by romanmikhailov** [comment]
@RealyUniqueName  Please add usage and limitation description in `README.md` and changes in `CHANGELOG.md`.

Under limitations I mean that classes each hx file in package should contain only one test case and name of test case class should be equal to class name.

**Comment by RealyUniqueName** [comment]
@fponticelli It can. I'll add it.
@romanmikhailov Good point, i will do it.

**Comment by RealyUniqueName** [comment]
Done

**Pull request merged**
