### PR TITLE
Enabled async tests for all platforms

### LINKED ISSUE #33: Async tests on other than flash or js targets
Is this really needed now when `haxe.Timer` is implemented on all platforms?
https://github.com/fponticelli/utest/blob/master/src/utest/TestHandler.hx#L62

I have async tests which fail untill i change `#if (flash || js)` to `#if (neko || flash || js)`

### PR DESCRIPTION
**Pull request by RealyUniqueName**
fixes #33

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
@fponticelli Do you have a plan for the next haxelib release?

**Comment by fponticelli** [comment]
Nops, but I can do it as soon you want.

**Comment by RealyUniqueName** [comment]
Yes, please.

**Comment by nadako** [comment]
Looks like this breaks old haxe which apparently doesn't have Timer.delay on all targets: https://travis-ci.org/nadako/hxjsonast/jobs/320209147#L554

**Comment by RealyUniqueName** [comment]
fixed

**Pull request merged**
