### PR TITLE
Implement `Assert.raisesMessage()`.

### LINKED ISSUE #107: Add method Assert.raisesMessage
To be able to assert a message is the expected one (useful when a class have method raising the same Exception but with different messages).

Example:

```haxe
import haxe.Exception;
import utest.Assert;
import utest.Test;
import my.package.View;

class ViewTest extends Test {
  function testEquals() {
    Assert.raises(() -> new View("not-exist"), Exception);
    Assert.raisesMessage(() -> new View("not-exist"), "view not-exist does not exist");
  }
}
```

### PR DESCRIPTION
**Pull request by player-03**
Resolves #107.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Proposed solution is quite narrow.  One may want to check other properties of exceptions.
So I implemented a more generic approach.

**Comment by player-03** [comment]
Your version is more complicated from the user's perspective, but I guess `raises()` is the simple/default use case, and the new function is specifically for times when the simple use case isn't enough.

The part I really don't like is the function name. `Assert.raisesCondition()` implies that a condition is being raised, whatever that means. You know what would be a good function name for this?

`raises()`.

Yep, that's right, I think the best solution is simply to merge this into the existing function. The only reason I didn't do that before is because there were already string arguments, so I couldn't add a new one. But you can absolutely insert an optional `(e:T)->Bool` argument in the middle without affecting any existing code. And the best time to make this change is now, before anyone starts using `raisesCondition()`.

**Comment by RealyUniqueName** [comment]
> The part I really don't like is the function name

I had hard times inventing a name for this method. 

>  I think the best solution is simply to merge this into the existing function

Yes, that was my initial idea, but unfortunately there's no simple way to have argument `e` typed in the condition callback if the `type` argument is `Any` or `Dynamic`.

Anyway it's not the final point. I hope a better solution will be found eventually.

**Comment by player-03** [comment]
Oh right, I forgot about `type`. Hmm.

My initial thought is change `type` to `Class<T>`, because nothing else produces useful information. The `isOfType()` check will return false for any other value, causing the test case to always fail, and there probably isn't anyone relying on that behavior. If they want a test that always fails, they're going to use `Assert.fail()` for clarity.

---

My second thought is that we could use macros. It would convert `Assert.raises(...)` to a try-catch block, with specifics depending on the number of arguments.

```haxe
//Assert.raises(() -> throw "exception");
try {
	throw "exception";
	utest.Assert.fail("exception not raised");
} catch(ex) {
	utest.Assert.pass();
}

//Assert.raises(() -> throw "exception", String);
try {
	throw "exception";
	utest.Assert.fail("exception not raised");
} catch(ex:String) {
	utest.Assert.pass();
} catch(ex) {
	utest.Assert.fail("expected throw String but it is " + ex);
}

//Assert.raises(() -> throw "exception", (e) -> e == "exception");
try {
	throw "exception";
	utest.Assert.fail("exception not raised");
} catch(e) {
	if(e == "exception") {
		utest.Assert.pass();
	} else {
		utest.Assert.fail("condition failed for value " + e);
	}
}

//Assert.raises(() -> throw "exception", String, (e) -> e.length == 9);
try {
	throw "exception";
	utest.Assert.fail("exception not raised");
} catch(e:String) {
	if(e.length == 9) {
		utest.Assert.pass();
	} else {
		utest.Assert.fail("condition failed for value " + e);
	}
} catch(ex) {
	utest.Assert.fail("expected throw String but it is " + ex);
}
```

The generated code will be inserted at the line `raises()` was called from, meaning the `PosInfos` will point to the correct spot. And since we're using `catch` to type-check, we don't need to worry about `ValueException`. The downside might be the complexity of the macro, though I'll see what I can do there.

**Pull request closed without merging**
