### PR TITLE
this is a very rough haxe 3.0 update just so all utest will compile. Some tests still fail, which need to be checked with more caution,

### PR DESCRIPTION
**Pull request by waneck**

### CODE REVIEW

**Comment by waneck** [comment]
small comment: this version should work fine on haxe 2.10- as well

**Comment by fponticelli** [comment]
Is this pull request much different from the haxe3 branch of the project?
Can you try making a pull request there?
I intend to keep the master branch for haxe2 and switch once haxe3 is official.

**Comment by waneck** [comment]
oh I didn't see a Haxe 3 branch! ;)
Anyway I've updated in a totally backwards-compatible way with haxe 2.10

I'll take a look at the Haxe3 branch later

**Comment by andyli** [comment]
Will a haxe3 compatible haxelib release soon?
We're using utest on NME with TravisCI, see https://github.com/haxenme/NME/pull/68.

**Comment by waneck** [comment]
It seems that the haxe3 branch already covers this. Thanks

**Pull request closed without merging**
