### PR TITLE
Fix issues in `Assert.exception()`.

### PR DESCRIPTION
**Pull request by player-03**
Since I already figured out the issues causing CI to fail, I figured I could apply the same solution to the new function. Plus I fixed the documentation, re-organized the code for clarity, and made the failure messages look better.

~~Edit: but apparently something else changed. I'm working on it.~~ Edit 2: it was target-specific weirdness.

Supersedes #127 and #128.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Thanks! What's the issue with C++?

**Comment by player-03** [comment]
It seems to implement enums slightly differently, making it unable to tell one enum type from another.

`Std.isOfType(Sample.Some('error'), haxe.ds.Option)` returns true, and at first that looks like it's because both have a constructor named `Some`. But then you try other values and they return true as well: `Std.isOfType(Sample.Rec(Sample.None), haxe.ds.Either)`.

So basically, the test can't be performed in C++.

**Comment by RealyUniqueName** [comment]
It's an issue of the Haxe itself: https://github.com/HaxeFoundation/haxe/issues/11442

**Comment by player-03** [comment]
Agreed.

**Pull request merged**
